build:
  version: "3.0"
spring:
  application:
    name: "cards"
  profiles:
    active: "qa"
cards:
  message: "ABC Bank cards related default webhook APIs"
  contactDetails:
    name: "Cards Developer - Developer"
    email: "cardsdeveloper@abcbank.com"
  onCallSupport:
    - (555) 555-1234
    - (555) 523-6758
