build:
  version: "3.0"

accounts:
  message: "Welcome to ABCBank accounts related local APIs "
  contactDetails:
    name: "accounts Doe - Developer"
    email: "accounts@msbytes.com"
  onCallSupport:
    - (555) 555-1234
    - (555) 523-1345