build:
  version: "3.0"
spring:
  application:
    name: "accounts"
  profiles:
    active: "qa"
accounts:
  message: "ABC Bank cards related local APIs"
  contactDetails:
    name: "Cards Developer - Developer"
    email: "cardsdeveloper@abcbank.com"
  onCallSupport:
    - (555) 555-1234
    - (555) 523-6758